In [1]:
## 내장 dataset 가져오기
# import sklearn
from sklearn.datasets import load_iris ## xxxx 위치에 다른 것을 넣으면 그에 대한 것이 import 된다.
iris=load_iris()
print(type(iris)) # bunch 는 dictionary 형태의 class이다.

<class 'sklearn.utils._bunch.Bunch'>


In [2]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

### scikit-learn 내장 데이터셋의 구성
- scikit-learn의 dataset은 딕셔너리 구조의 Bunch 클래스 객체이다.
    - keys() 함수로 key값들을 조회
- 구성
    - **target_names**: 예측하려는 값(class)을 가진 문자열 배열
    - **target**: Label(출력데이터)
    - **data**: Feature(입력변수)
    - **feature_names**: 입력변수 각 항목의 이름
    - **DESCR**: 데이터셋에 대한 설명

In [4]:
X=iris['data']
print(type(X),X.shape)
X[:5] ## indexing 가능

<class 'numpy.ndarray'> (150, 4)


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [5]:
# feature의 이름
iris["feature_names"]

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
# 출력 data=label, target
y=iris['target'] # iris.target
print(type(y), y.shape)
y[:5]

<class 'numpy.ndarray'> (150,)


array([0, 0, 0, 0, 0])

In [7]:
# y값 class (고유값)
import numpy as np
np.unique(y,return_counts=True)

(array([0, 1, 2]), array([50, 50, 50], dtype=int64))