In [1]:
## 내장 dataset 가져오기
# import sklearn
from sklearn.datasets import load_iris ## xxxx 위치에 다른 것을 넣으면 그에 대한 것이 import 된다.
iris=load_iris()
print(type(iris)) # bunch 는 dictionary 형태의 class이다.

<class 'sklearn.utils._bunch.Bunch'>


In [2]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

### scikit-learn 내장 데이터셋의 구성
- scikit-learn의 dataset은 딕셔너리 구조의 Bunch 클래스 객체이다.
    - keys() 함수로 key값들을 조회
- 구성
    - **target_names**: 예측하려는 값(class)을 가진 문자열 배열
    - **target**: Label(출력데이터)
    - **data**: Feature(입력변수)
    - **feature_names**: 입력변수 각 항목의 이름
    - **DESCR**: 데이터셋에 대한 설명

In [3]:
X=iris['data']
print(type(X),X.shape)
X[:5] ## indexing 가능

<class 'numpy.ndarray'> (150, 4)


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [4]:
# feature의 이름
iris["feature_names"]

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [5]:
# 출력 data=label, target
y=iris['target'] # iris.target
print(type(y), y.shape)
y[:5]

<class 'numpy.ndarray'> (150,)


array([0, 0, 0, 0, 0])

In [6]:
# y값 class (고유값)
import numpy as np
np.unique(y,return_counts=True)

(array([0, 1, 2]), array([50, 50, 50], dtype=int64))

In [7]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [8]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [9]:
iris['data'],iris['feature_names']

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [10]:
import pandas as pd

In [11]:
df=pd.DataFrame(iris['data'],columns=iris['feature_names'])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [12]:
## numpy method
# nparray 생성
np.zeros(shape=10) # shape=정수 : 1차원 배열
np.zeros(shape=(6, 3, 2)) #shape=튜플: 다차원 배열
np.zeros(shape=(3,2), dtype='int32')
np.ones(shape=5)
np.ones(shape=(4, 3))
np.full(shape=6, fill_value=100) #dtype: fill_value에 값에 맞춰서 설정된다.
np.full(shape=(3,2), fill_value=True)
np.zeros_like(a1) #a1과 동일한 shape의 0을 원소로 가지는 배열을 생성.
np.ones_like(a2)
np.full_like(a3, fill_value=100)

# random
np.random.rand()
np.random.rand(5)  # 1차원배열 (5, )
np.random.rand(3, 5) # 2차원배열 (3, 5)
np.random.rand(2, 3, 4)
np.random.normal(loc=0.0, scale=1.0, size=None)
# loc: 평균, scale: 표준편차 -> 2가지 생략시 표준정규분포

#reshape
np.arange(30).reshape(5.6) #(30,) ->(5,6)

NameError: name 'a1' is not defined

In [ ]:
np.where(iris['target']==0,"setoas",np.where(iris['target']==1,'versicolor','verginica'))

# 제외해야하는 값들
이상치(Outlier) - 튀는 값, 패턴을 벗어난 값 \
오류값 - 잘못 수집된 값, 결측치로 변환후 처리 \
극단치 - 정상적이지만 다른값들과 다른 패턴을 가지는 값\


In [1]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '컴퓨터', '컴퓨터', '냉장고', '에어콘',  'TV', '에어콘']
le=LabelEncoder()

le.fit(items) # items 를 이용해서 어떻게 바꿀지 학습

item_label=le.transform(items)
item_label

array([0, 1, 3, 3, 1, 2, 0, 2])

In [2]:
le.classes_ # fit 이후에 사용가능
# 출력된 array의 index가 encoding된 정수를 의미

array(['TV', '냉장고', '에어콘', '컴퓨터'], dtype='<U3')

In [4]:
# fit과 transform 대상이 같으면 동시에 사용 가능
item_label2=le.fit_transform(items)
item_label2

array([0, 1, 3, 3, 1, 2, 0, 2], dtype=int64)

In [6]:
class_names = ["냉장고", "TV", "에어콘", "컴퓨터", "노트북", "스마트폰"]
le3 = LabelEncoder()
le3.fit(class_names)
item_label3=le3.transform(class_names)
item_label3

array([1, 0, 4, 5, 2, 3])

In [7]:
item_label4=le3.transform(items)
item_label4

array([0, 1, 5, 5, 1, 4, 0, 4])